name: GoTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose -f docker-compose-test.yml up -d
    - name: Execute go test
      run: docker-compose exec -T app bash -c "cd cmd; go test ./..."
